apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db
          image: mongo:4.4.6-bionic
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.user }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-pass
                  key: key
          ports:
            - containerPort: 27017
          volumeMounts:
          - name: mongodb-persistent-storage
            mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: pvc
