apiVersion: v1
kind: Service
metadata:
  name: app-deployment-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: app-deploy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-deployment-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app:  mongo-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: app-me-deployment-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: app-me
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
