apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: gold
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
